### ISSUE TITLE
undefined symbol: _PyGen_Send on python 3.10 -- upstream bug in lxml

### ISSUE THREAD

**Issue by spazm-ma** [zdave/openconnect-gp-okta#17]
> `ImportError: [...] /python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send` 

lxml is pinned to version 4.6.2 in `requirements.txt` which does not work with python 3.10.

lxml [fixed this bug](https://bugs.launchpad.net/lxml/+bug/1904900) in 4.6.3 

Upgrading to current (4.8.0) worked for me.  bumping from 4.6.2 to 4.6.3 would probably be sufficient.

upgrading my virtual environment:
```
pip install lxml --upgrade
```

**Comment by zdave** [comment]
Bumped all the package versions. Working for me now with Python 3.10. Thanks for the report!
